#! /bin/csh -f

# Run mrmsStats

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2020 11 01 00 00 00" --end "2020 11 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202011.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2020 12 01 00 00 00" --end "2020 12 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202012.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 01 01 00 00 00" --end "2021 01 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202101.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 02 01 00 00 00" --end "2021 02 28 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202102.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 03 01 00 00 00" --end "2021 03 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202103.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 04 01 00 00 00" --end "2021 04 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202104.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 05 01 00 00 00" --end "2021 05 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202105.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 06 01 00 00 00" --end "2021 06 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202106.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 07 01 00 00 00" --end "2021 07 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202107.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 08 01 00 00 00" --end "2021 08 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202108.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 09 01 00 00 00" --end "2021 09 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202109.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 10 01 00 00 00" --end "2021 10 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202110.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 11 01 00 00 00" --end "2021 11 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202111.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2021 12 01 00 00 00" --end "2021 12 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202112.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 01 01 00 00 00" --end "2022 01 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202201.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 02 01 00 00 00" --end "2022 02 28 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202202.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 03 01 00 00 00" --end "2022 03 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202203.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 04 01 00 00 00" --end "2022 04 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202204.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 05 01 00 00 00" --end "2022 05 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202205.log &

python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 06 01 00 00 00" --end "2022 06 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202206.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 07 01 00 00 00" --end "2022 07 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202207.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 08 01 00 00 00" --end "2022 08 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202208.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 09 01 00 00 00" --end "2022 09 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202209.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 10 01 00 00 00" --end "2022 10 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202210.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 11 01 00 00 00" --end "2022 11 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202211.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2022 12 01 00 00 00" --end "2022 12 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202212.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 01 01 00 00 00" --end "2023 01 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202301.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 02 01 00 00 00" --end "2023 02 28 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202302.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 03 01 00 00 00" --end "2023 03 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202303.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 04 01 00 00 00" --end "2023 04 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202304.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 05 01 00 00 00" --end "2023 05 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202305.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 06 01 00 00 00" --end "2023 06 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202306.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 07 01 00 00 00" --end "2023 07 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202307.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 08 01 00 00 00" --end "2023 08 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202308.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 09 01 00 00 00" --end "2023 09 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202309.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 10 01 00 00 00" --end "2023 10 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202310.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 11 01 00 00 00" --end "2023 11 30 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202311.log &

#python ~/git/lrose-ecco/ecco/dataProcessing/mrmsStats.py --start "2023 12 01 00 00 00" --end "2023 12 31 23 59 59" >& /scr/cirrus2/rsfdata/projects/nexrad-mrms/statMats/logFiles/pyStats_202312.log &
